services:
    test-db-server:
        image: mongo:latest
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=123
            - MONGO_INITDB_DATABASE=test
        ports:
            - 27017:27017
        volumes:
            - $PWD/mongodata:/data/db 